Controllers/ClientPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SoloMastersWeb.Data;
using SoloMastersWeb.Models;

namespace SoloMastersWeb.Controllers
{
    public class ClientPostsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClientPostsController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize]
        //Vista Maestros
        public async Task<IActionResult> MasterView()
        {
            return View(await _context.avisoClientes.ToListAsync());
        }

        [Authorize]
        public async Task<IActionResult> ClientOwnerPosts(String userFilter)//filtro de avisos de usuario
        {
            return View("IndexOwner", await _context.avisoClientes.Where(b => b.clientOwner.Contains(userFilter)).ToListAsync());
        }

        [Authorize]
        public async Task<IActionResult> BuscadorAviso(String PalabraBuscada) //buscador
        {
            return View("MasterView", await _context.avisoClientes.Where(b => b.clientPostTitle.Contains(PalabraBuscada)).ToListAsync());
           
        }



        [Authorize]
        // GET: ClientPosts (all)
        public async Task<IActionResult> Index()
        {
            return View(await _context.avisoClientes.ToListAsync());
        }

        [Authorize]
        // GET: ClientPosts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clientPost = await _context.avisoClientes
                .FirstOrDefaultAsync(m => m.clientPostId == id);
            if (clientPost == null)
            {
                return NotFound();
            }

            return View(clientPost);
        }

        [Authorize]
        //MasterView Details
        public async Task<IActionResult> MasterDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clientPost = await _context.avisoClientes
                .FirstOrDefaultAsync(m => m.clientPostId == id);
            if (clientPost == null)
            {
                return NotFound();
            }

            return View(clientPost);
        }

        [Authorize]
        // GET: ClientPosts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ClientPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("clientPostId,clientPostTitle,clientPostdescription,clientOwner,clientePostDate")] ClientPost clientPost)
        {
            if (ModelState.IsValid)
            {
                _context.Add(clientPost);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(clientPost);
        }

        [Authorize]
        // GET: ClientPosts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clientPost = await _context.avisoClientes.FindAsync(id);
            if (clientPost == null)
            {
                return NotFound();
            }
            return View(clientPost);
        }

        // POST: ClientPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("clientPostId,clientPostTitle,clientPostdescription,clientOwner,clientePostDate")] ClientPost clientPost)
        {
            if (id != clientPost.clientPostId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(clientPost);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientPostExists(clientPost.clientPostId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(clientPost);
        }

        [Authorize]
        // GET: ClientPosts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clientPost = await _context.avisoClientes
                .FirstOrDefaultAsync(m => m.clientPostId == id);
            if (clientPost == null)
            {
                return NotFound();
            }

            return View(clientPost);
        }

        // POST: ClientPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var clientPost = await _context.avisoClientes.FindAsync(id);
            _context.avisoClientes.Remove(clientPost);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientPostExists(int id)
        {
            return _context.avisoClientes.Any(e => e.clientPostId == id);
        }
    }
}

Controllers/MasterPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SoloMastersWeb.Data;
using SoloMastersWeb.Models;

namespace SoloMastersWeb.Controllers
{
    public class MasterPostsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MasterPostsController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize]
        //Vista clientes
        public async Task<IActionResult> ClientView()
        {
            return View(await _context.avisoMaestros.ToListAsync());
        }

        [Authorize]
        public async Task<IActionResult> MasterOwnerPost(String userFilter)//filtro de servicios de maestro
        {
            return View("IndexMasterOwner", await _context.avisoMaestros.Where(b => b.masterOwner.Contains(userFilter)).ToListAsync());
        }

        [Authorize]
        public async Task<IActionResult> BuscadorServicio(String PalabraBuscada) //buscador de servicios
        {
            return View("ClientView", await _context.avisoMaestros.Where(b => b.masterPostTitle.Contains(PalabraBuscada)).ToListAsync());

        }

        [Authorize]
        // GET: MasterPosts
        public async Task<IActionResult> Index()
        {
            return View(await _context.avisoMaestros.ToListAsync());
        }

        [Authorize]
        // GET: MasterPosts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var masterPost = await _context.avisoMaestros
                .FirstOrDefaultAsync(m => m.masterPostId == id);
            if (masterPost == null)
            {
                return NotFound();
            }

            return View(masterPost);
        }

        [Authorize]
        // ClientDetails
        public async Task<IActionResult> ClientDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var masterPost = await _context.avisoMaestros
                .FirstOrDefaultAsync(m => m.masterPostId == id);
            if (masterPost == null)
            {
                return NotFound();
            }

            return View(masterPost);
        }


        [Authorize]
        // GET: MasterPosts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MasterPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("masterPostId,masterPostTitle,masterPostDescription,masterOwner,masterPostDate,imgUrl")] MasterPost masterPost)
        {
            if (ModelState.IsValid)
            {
                _context.Add(masterPost);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(masterPost);
        }

        [Authorize]
        // GET: MasterPosts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var masterPost = await _context.avisoMaestros.FindAsync(id);
            if (masterPost == null)
            {
                return NotFound();
            }
            return View(masterPost);
        }

        // POST: MasterPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("masterPostId,masterPostTitle,masterPostDescription,masterOwner,masterPostDate,imgUrl")] MasterPost masterPost)
        {
            if (id != masterPost.masterPostId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(masterPost);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MasterPostExists(masterPost.masterPostId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(masterPost);
        }

        [Authorize]
        // GET: MasterPosts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var masterPost = await _context.avisoMaestros
                .FirstOrDefaultAsync(m => m.masterPostId == id);
            if (masterPost == null)
            {
                return NotFound();
            }

            return View(masterPost);
        }

        [Authorize]
        // POST: MasterPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var masterPost = await _context.avisoMaestros.FindAsync(id);
            _context.avisoMaestros.Remove(masterPost);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MasterPostExists(int id)
        {
            return _context.avisoMaestros.Any(e => e.masterPostId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SoloMastersWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    @if (SignInManager.IsSignedIn(User))
    {
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-warning border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/img/logo.jpg" width="50" height="50"></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Sobre Nosotros</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MasterPosts" asp-action="ClientView">Buscar Maestros</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MasterPosts" asp-action="Index">Ofrecer tus servicios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ClientPosts" asp-action="Index">Ofrecer trabajo</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ClientPosts" asp-action="MasterView">Buscar clientes</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

    }
    else
    {
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-warning border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/img/logo.jpg" width="50" height="50"></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Sobre Nosotros</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    }

    <footer class="border-top footer text-muted bg-warning">
        <div class="container">
            &copy; 2021 - SoloMasters.cl - <a asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>